
/** required package class namespace */
package year2019.cs40s.systemfilemanager;


/**
 * FileToolsUI.java - the user interface for the file tools application
 *
 * @author Mr. Wachs 
 * @since 21-Sep-2018 
 */
public class FileToolsUI extends javax.swing.JFrame 
{
    
    private FileToolsUIController controller;

    /**  
     * Default constructor for the class, creates new form UnoUI 
     */
    public FileToolsUI() {
        initComponents();
        controller = new FileToolsUIController(
                jButton1,jButton2,jButton3,jButton4,jButton5,
                jLabel2,jLabel5,jPanel1,jPanel2,
                jTextArea1,jTextArea2,jTextArea4,jTextArea6,jTextArea7,
                jTextArea8,jTextArea9,
                this
        );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea14 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Operating System File Tools:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 980, 50);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("File Duplicator"));
        jPanel1.setLayout(null);

        jButton1.setText("Select Target File / Folder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 80, 190, 50);

        jLabel5.setText("Select a folder, then a class list text file, then click execute");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 200, 780, 50);

        jButton3.setText("Execute File Duplication");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 200, 190, 50);

        jButton2.setText("Select Class List To Use");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 140, 190, 50);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(java.awt.SystemColor.menu);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("These tools will take an existing file (which you select from a target file with folder) below and duplicates it (makes copies) with the first part of the name of the file matching with a series of names selected with a button below (the class list). Then a button executes the operation");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 980, 40);

        jTextArea8.setBackground(java.awt.SystemColor.menu);
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jTextArea8.setRows(5);
        jTextArea8.setText("...");
        jScrollPane8.setViewportView(jTextArea8);

        jPanel1.add(jScrollPane8);
        jScrollPane8.setBounds(210, 140, 780, 50);

        jTextArea9.setBackground(java.awt.SystemColor.menu);
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jTextArea9.setRows(5);
        jTextArea9.setText("...");
        jScrollPane9.setViewportView(jTextArea9);

        jPanel1.add(jScrollPane9);
        jScrollPane9.setBounds(210, 80, 780, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 120, 1000, 260);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Folder Copier"));
        jPanel2.setLayout(null);

        jButton4.setText("Select Destination Folder (to copy empty folder structure to)");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(10, 130, 440, 50);

        jButton5.setText("Select Target Folder (with subfolders) to copy");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(10, 70, 440, 50);

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(java.awt.SystemColor.menu);
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("These tools will take an existing file (which you select from a target file with folder) below and duplicates it (makes copies) with the first part of the name of the file matching with a series of names selected with a button below (the class list). Then a button executes the operation");
        jTextArea4.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTextArea4);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(10, 30, 980, 40);

        jTextArea6.setBackground(java.awt.SystemColor.menu);
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("...");
        jScrollPane6.setViewportView(jTextArea6);

        jPanel2.add(jScrollPane6);
        jScrollPane6.setBounds(460, 130, 530, 50);

        jTextArea7.setBackground(java.awt.SystemColor.menu);
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText("...");
        jScrollPane7.setViewportView(jTextArea7);

        jPanel2.add(jScrollPane7);
        jScrollPane7.setBounds(460, 70, 530, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 590, 1000, 190);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(java.awt.SystemColor.menu);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Welcome to the File Tools application, use these tools to assist with managing operating system files. Tasks include folder copying and file renaming and creation. Use the buttons and follow the instructions below:");
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 70, 980, 40);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("File and Folder Creator"));
        jPanel4.setLayout(null);

        jButton9.setText("Start Process");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9);
        jButton9.setBounds(10, 100, 190, 80);

        jScrollPane12.setBorder(null);
        jScrollPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane12.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea12.setEditable(false);
        jTextArea12.setBackground(java.awt.SystemColor.menu);
        jTextArea12.setColumns(20);
        jTextArea12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea12.setLineWrap(true);
        jTextArea12.setRows(5);
        jTextArea12.setText("This tool will select a text file which represents a list of all students in the class. Then the user will select multiple files (hold CTRL or SHIFT to select multiple files) that the tool will make copies of and then fill the sub-folders this tool will be creating with those file copies (the original files will remain untouched). This tool will also rename the beginning of each of those files to match the name of the students. Then the user will select a parent folder which represents the top folder that will be used to be filled with a number of sub-folders (one for each student in the list - named after the student names) and the file copies. ");
        jTextArea12.setWrapStyleWord(true);
        jScrollPane12.setViewportView(jTextArea12);

        jPanel4.add(jScrollPane12);
        jScrollPane12.setBounds(10, 30, 980, 60);

        jTextArea14.setBackground(java.awt.SystemColor.menu);
        jTextArea14.setColumns(20);
        jTextArea14.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jTextArea14.setRows(5);
        jTextArea14.setText("...");
        jScrollPane14.setViewportView(jTextArea14);

        jPanel4.add(jScrollPane14);
        jScrollPane14.setBounds(210, 100, 780, 80);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 390, 1000, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller.selectFileAndFolder();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        controller.execute();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controller.selectClassList();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        controller.selectTarget();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.shutDown();
    }//GEN-LAST:event_formWindowClosing

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        controller.selectDestination();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        FolderSystem folderSystem = new FolderSystem(jTextArea14);
    }//GEN-LAST:event_jButton9ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    // End of variables declaration//GEN-END:variables

}
