/*
 *  Mr. Wachs' classes - Java Computer Science learning file MainUIView.java
 *  for project FinalExamples on 14-May-2019 at 8:20:20 AM by lawrence.wachs
 */


/** required package class namespace */
package year2019.cs40s.awards.userinterfaces.views;

import year2019.cs40s.awards.userinterfaces.controllers.MainUIController;


/**
 * MainUIView.java - 
 *
 * @author Mr. Wachs 
 * @since 14-May-2019 
 */
public class MainUIView extends javax.swing.JFrame 
{

    private MainUIController controller;
    
    /** Creates new form MainUIView */
    public MainUIView() {
        initComponents();
        controller = new MainUIController(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTitleLabel = new javax.swing.JLabel();
        mainInstructionsLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        manageSessionsPanel = new javax.swing.JPanel();
        newSessionButton = new javax.swing.JButton();
        openSessionButton = new javax.swing.JButton();
        saveSessionButton = new javax.swing.JButton();
        importDataButton = new javax.swing.JButton();
        manageSessionsLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mainTitleLabel.setText("Awards Assistant");
        getContentPane().add(mainTitleLabel);
        mainTitleLabel.setBounds(10, 10, 760, 40);

        mainInstructionsLabel.setText("Instructions here...");
        getContentPane().add(mainInstructionsLabel);
        mainInstructionsLabel.setBounds(10, 60, 760, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Current Awards and Students:"));
        jPanel1.setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 70, 750, 100);

        jButton11.setText("See All Current Courses");
        jPanel1.add(jButton11);
        jButton11.setBounds(10, 180, 250, 50);

        jButton12.setText("See Full Award List");
        jPanel1.add(jButton12);
        jButton12.setBounds(260, 180, 250, 50);

        jButton1.setText("Manage Award Rules");
        jPanel1.add(jButton1);
        jButton1.setBounds(510, 180, 250, 50);

        jLabel5.setText("Instructions here...");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 20, 740, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 480, 780, 240);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Current Student and Grade Totals:"));
        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Title 4");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Title 5");
        }

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 750, 100);

        jButton4.setText("SORT");
        jPanel2.add(jButton4);
        jButton4.setBounds(20, 180, 130, 23);

        jButton5.setText("SORT");
        jPanel2.add(jButton5);
        jButton5.setBounds(170, 180, 130, 23);

        jButton6.setText("SORT");
        jPanel2.add(jButton6);
        jButton6.setBounds(320, 180, 130, 23);

        jButton7.setText("SORT");
        jPanel2.add(jButton7);
        jButton7.setBounds(470, 180, 130, 23);

        jButton3.setText("SORT");
        jPanel2.add(jButton3);
        jButton3.setBounds(620, 180, 130, 23);

        jLabel4.setText("Instructions here...");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 20, 740, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 250, 780, 220);

        manageSessionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Manage Application Sessions"));
        manageSessionsPanel.setLayout(null);

        newSessionButton.setText("Start New Session");
        manageSessionsPanel.add(newSessionButton);
        newSessionButton.setBounds(10, 70, 190, 50);

        openSessionButton.setText("Open Previous Session");
        manageSessionsPanel.add(openSessionButton);
        openSessionButton.setBounds(200, 70, 190, 50);

        saveSessionButton.setText("Save Current Session");
        manageSessionsPanel.add(saveSessionButton);
        saveSessionButton.setBounds(390, 70, 190, 50);

        importDataButton.setText("Import Data From File");
        manageSessionsPanel.add(importDataButton);
        importDataButton.setBounds(580, 70, 190, 50);

        manageSessionsLabel.setText("Instructions here...");
        manageSessionsPanel.add(manageSessionsLabel);
        manageSessionsLabel.setBounds(10, 20, 740, 40);

        getContentPane().add(manageSessionsPanel);
        manageSessionsPanel.setBounds(10, 110, 780, 130);

        jMenu1.setText("Session");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Start New Session");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Open Previous Session");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Save Current Session");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Import Data From File");
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Exit");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Students");

        jMenuItem6.setText("Sort by First Name");
        jMenu2.add(jMenuItem6);

        jMenuItem10.setText("Sort by Last Name");
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Sort by Grade");
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Sort by Total # of Courses");
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Sort by Overall GPA");
        jMenu2.add(jMenuItem13);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Awards");

        jMenuItem7.setText("See all current courses");
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("See full award list");
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Manage award rules");
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton importDataButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel mainInstructionsLabel;
    private javax.swing.JLabel mainTitleLabel;
    private javax.swing.JLabel manageSessionsLabel;
    private javax.swing.JPanel manageSessionsPanel;
    private javax.swing.JButton newSessionButton;
    private javax.swing.JButton openSessionButton;
    private javax.swing.JButton saveSessionButton;
    // End of variables declaration//GEN-END:variables

}
