package yearOthers.triangle;


import java.awt.Graphics;
import java.awt.event.MouseEvent;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FractalCanvasGUI.java
 *
 * Created on 25-Jan-2012, 12:00:23 PM
 */
/**
 *
 * @author lwachs
 */
public class FractalCanvasGUI extends java.awt.Frame {

    /** Creates new form FractalCanvasGUI */
    public FractalCanvasGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        mouseDown(evt);
    }//GEN-LAST:event_formMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        keyDown();
    }//GEN-LAST:event_formKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void keyDown() {
        FractalLogic.keyDown();
    }

    private void mouseDown(MouseEvent e) {
        FractalLogic.mouseDown(e);
    }
    
    @Override
    public void update(Graphics g) {        
        if (FractalLogic.isRandom == false) 
            FractalLogic.foregroundColor = Box.randomColor();
        g.setColor(FractalLogic.foregroundColor);
        g.fillOval(FractalLogic.x-(FractalLogic.dotSize/2),
                   FractalLogic.y-(FractalLogic.dotSize/2),
                   FractalLogic.dotSize,FractalLogic.dotSize);
    }

}
