package yearOthers.seatingplan;

/**
 * SeatingPlan.java
 * Created on 10-Dec-2010, 9:34:07 AM
 * @author lwachs
 */
public class SeatingPlan extends javax.swing.JFrame {

    SeatingPlanner plan;

    /** Creates new form SeatingPlan */
    public SeatingPlan() {
        initComponents();
        plan = new SeatingPlanner(this,
            lblSeat1,  lblSeat2,  lblSeat3,  lblSeat4,  lblSeat5,
            lblSeat6,  lblSeat7,  lblSeat8,  lblSeat9,  lblSeat10,
            lblSeat11, lblSeat12, lblSeat13, lblSeat14, lblSeat15,
            lblSeat16, lblSeat17, lblSeat18, lblSeat19, lblSeat20,
            lblSeat21, lblSeat22, lblSeat23, lblSeat24, lblSeat25,
            lblSeat26, lblSeat27, lblSeat28, lblSeat29, lblSeat30,
            fraBackground);
        plan.setGUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fraBackground = new javax.swing.JPanel();
        lblSeat5 = new javax.swing.JLabel();
        lblScreen = new javax.swing.JLabel();
        lblSeat22 = new javax.swing.JLabel();
        lblSeat21 = new javax.swing.JLabel();
        lblSeat17 = new javax.swing.JLabel();
        lblSeat23 = new javax.swing.JLabel();
        lblSeat2 = new javax.swing.JLabel();
        lblSeat3 = new javax.swing.JLabel();
        lblSeat4 = new javax.swing.JLabel();
        lblSeat20 = new javax.swing.JLabel();
        lblSeat19 = new javax.swing.JLabel();
        lblSeat18 = new javax.swing.JLabel();
        lblSeat6 = new javax.swing.JLabel();
        lblSeat16 = new javax.swing.JLabel();
        lblSeat15 = new javax.swing.JLabel();
        lblSeat14 = new javax.swing.JLabel();
        lblSeat13 = new javax.swing.JLabel();
        lblSeat12 = new javax.swing.JLabel();
        lblSeat11 = new javax.swing.JLabel();
        lblSeat10 = new javax.swing.JLabel();
        lblSeat9 = new javax.swing.JLabel();
        lblSeat8 = new javax.swing.JLabel();
        lblSeat7 = new javax.swing.JLabel();
        lblSeat1 = new javax.swing.JLabel();
        lblSeat30 = new javax.swing.JLabel();
        lblSeat27 = new javax.swing.JLabel();
        lblSeat26 = new javax.swing.JLabel();
        lblSeat25 = new javax.swing.JLabel();
        lblSeat24 = new javax.swing.JLabel();
        lblSeat28 = new javax.swing.JLabel();
        lblSeat29 = new javax.swing.JLabel();
        lblDoor = new javax.swing.JLabel();
        lblRandom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fraBackground.setBackground(new java.awt.Color(255, 255, 255));
        fraBackground.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fraBackground.setLayout(null);

        lblSeat5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat5.setText("SEAT");
        lblSeat5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat5);
        lblSeat5.setBounds(980, 80, 80, 60);

        lblScreen.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblScreen.setForeground(new java.awt.Color(255, 255, 255));
        lblScreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScreen.setText("SCREEN");
        lblScreen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblScreenMousePressed(evt);
            }
        });
        fraBackground.add(lblScreen);
        lblScreen.setBounds(130, 410, 200, 160);

        lblSeat22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat22.setText("SEAT");
        lblSeat22.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat22);
        lblSeat22.setBounds(10, 380, 80, 60);

        lblSeat21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat21.setText("SEAT");
        lblSeat21.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat21);
        lblSeat21.setBounds(10, 320, 80, 60);

        lblSeat17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat17.setText("SEAT");
        lblSeat17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat17);
        lblSeat17.setBounds(10, 80, 80, 60);

        lblSeat23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat23.setText("SEAT");
        lblSeat23.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat23);
        lblSeat23.setBounds(670, 180, 80, 60);

        lblSeat2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat2.setText("SEAT");
        lblSeat2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat2);
        lblSeat2.setBounds(980, 260, 80, 60);

        lblSeat3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat3.setText("SEAT");
        lblSeat3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat3);
        lblSeat3.setBounds(980, 200, 80, 60);

        lblSeat4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat4.setText("SEAT");
        lblSeat4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat4);
        lblSeat4.setBounds(980, 140, 80, 60);

        lblSeat20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat20.setText("SEAT");
        lblSeat20.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat20);
        lblSeat20.setBounds(10, 260, 80, 60);

        lblSeat19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat19.setText("SEAT");
        lblSeat19.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat19);
        lblSeat19.setBounds(10, 200, 80, 60);

        lblSeat18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat18.setText("SEAT");
        lblSeat18.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat18);
        lblSeat18.setBounds(10, 140, 80, 60);

        lblSeat6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat6.setText("SEAT");
        lblSeat6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat6);
        lblSeat6.setBounds(900, 10, 80, 60);

        lblSeat16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat16.setText("SEAT");
        lblSeat16.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat16);
        lblSeat16.setBounds(100, 10, 80, 60);

        lblSeat15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat15.setText("SEAT");
        lblSeat15.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat15);
        lblSeat15.setBounds(180, 10, 80, 60);

        lblSeat14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat14.setText("SEAT");
        lblSeat14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat14);
        lblSeat14.setBounds(260, 10, 80, 60);

        lblSeat13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat13.setText("SEAT");
        lblSeat13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat13);
        lblSeat13.setBounds(340, 10, 80, 60);

        lblSeat12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat12.setText("SEAT");
        lblSeat12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat12);
        lblSeat12.setBounds(420, 10, 80, 60);

        lblSeat11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat11.setText("SEAT");
        lblSeat11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat11);
        lblSeat11.setBounds(500, 10, 80, 60);

        lblSeat10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat10.setText("SEAT");
        lblSeat10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat10);
        lblSeat10.setBounds(580, 10, 80, 60);

        lblSeat9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat9.setText("SEAT");
        lblSeat9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat9);
        lblSeat9.setBounds(660, 10, 80, 60);

        lblSeat8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat8.setText("SEAT");
        lblSeat8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat8);
        lblSeat8.setBounds(740, 10, 80, 60);

        lblSeat7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat7.setText("SEAT");
        lblSeat7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat7);
        lblSeat7.setBounds(820, 10, 80, 60);

        lblSeat1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat1.setText("SEAT");
        lblSeat1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat1);
        lblSeat1.setBounds(980, 320, 80, 60);

        lblSeat30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat30.setText("SEAT");
        lblSeat30.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat30);
        lblSeat30.setBounds(590, 240, 80, 60);

        lblSeat27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat27.setText("SEAT");
        lblSeat27.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat27);
        lblSeat27.setBounds(350, 180, 80, 60);

        lblSeat26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat26.setText("SEAT");
        lblSeat26.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat26);
        lblSeat26.setBounds(430, 120, 80, 60);

        lblSeat25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat25.setText("SEAT");
        lblSeat25.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat25);
        lblSeat25.setBounds(510, 120, 80, 60);

        lblSeat24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat24.setText("SEAT");
        lblSeat24.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat24);
        lblSeat24.setBounds(590, 120, 80, 60);

        lblSeat28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat28.setText("SEAT");
        lblSeat28.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat28);
        lblSeat28.setBounds(430, 240, 80, 60);

        lblSeat29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeat29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/Seat.png"))); // NOI18N
        lblSeat29.setText("SEAT");
        lblSeat29.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSeat29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fraBackground.add(lblSeat29);
        lblSeat29.setBounds(510, 240, 80, 60);

        lblDoor.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblDoor.setForeground(new java.awt.Color(255, 255, 255));
        lblDoor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yearOthers/seatingplan/door.png"))); // NOI18N
        lblDoor.setText("DOOR");
        lblDoor.setFocusable(false);
        lblDoor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDoor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDoorMousePressed(evt);
            }
        });
        fraBackground.add(lblDoor);
        lblDoor.setBounds(840, 450, 80, 120);

        lblRandom.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblRandom.setForeground(new java.awt.Color(255, 255, 255));
        lblRandom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRandom.setText("SEREDA");
        lblRandom.setFocusable(false);
        lblRandom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblRandom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRandomMousePressed(evt);
            }
        });
        fraBackground.add(lblRandom);
        lblRandom.setBounds(400, 380, 300, 190);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fraBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fraBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRandomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRandomMousePressed
        plan.randomSeating();
    }//GEN-LAST:event_lblRandomMousePressed

    private void lblScreenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScreenMousePressed
        plan.randomize();
    }//GEN-LAST:event_lblScreenMousePressed

    private void lblDoorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoorMousePressed
        plan.exitProgram();
    }//GEN-LAST:event_lblDoorMousePressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeatingPlan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fraBackground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDoor;
    private javax.swing.JLabel lblRandom;
    private javax.swing.JLabel lblScreen;
    private javax.swing.JLabel lblSeat1;
    private javax.swing.JLabel lblSeat10;
    private javax.swing.JLabel lblSeat11;
    private javax.swing.JLabel lblSeat12;
    private javax.swing.JLabel lblSeat13;
    private javax.swing.JLabel lblSeat14;
    private javax.swing.JLabel lblSeat15;
    private javax.swing.JLabel lblSeat16;
    private javax.swing.JLabel lblSeat17;
    private javax.swing.JLabel lblSeat18;
    private javax.swing.JLabel lblSeat19;
    private javax.swing.JLabel lblSeat2;
    private javax.swing.JLabel lblSeat20;
    private javax.swing.JLabel lblSeat21;
    private javax.swing.JLabel lblSeat22;
    private javax.swing.JLabel lblSeat23;
    private javax.swing.JLabel lblSeat24;
    private javax.swing.JLabel lblSeat25;
    private javax.swing.JLabel lblSeat26;
    private javax.swing.JLabel lblSeat27;
    private javax.swing.JLabel lblSeat28;
    private javax.swing.JLabel lblSeat29;
    private javax.swing.JLabel lblSeat3;
    private javax.swing.JLabel lblSeat30;
    private javax.swing.JLabel lblSeat4;
    private javax.swing.JLabel lblSeat5;
    private javax.swing.JLabel lblSeat6;
    private javax.swing.JLabel lblSeat7;
    private javax.swing.JLabel lblSeat8;
    private javax.swing.JLabel lblSeat9;
    // End of variables declaration//GEN-END:variables

}
