
/** required package class namespace */
package year2019.cs30s.email;


/**
 * UserInterface.java - the user interface model for the email application
 *
 * @author Mr. Wachs 
 * @since 16-Nov-2018 
 */
public class UserInterface extends javax.swing.JFrame 
{

    private UIManager manager;
    
    /** Creates new form UserInterface */
    public UserInterface() {
        initComponents();
        manager = new UIManager(jTextArea1,jPasswordField1,jTextField1,
                jTextField2,jTextField3,this);
    }

    // <editor-fold defaultstate="collapsed" desc="NetBeans Generated Code">   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("From:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 70, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(80, 10, 240, 20);

        jLabel3.setText("To:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 70, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(80, 70, 240, 20);

        jLabel4.setText("Subject:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 100, 70, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(80, 100, 240, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 310, 140);

        jButton1.setText("SEND");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 280, 310, 40);

        jLabel5.setText("Password:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 40, 70, 20);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(80, 40, 240, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    // </editor-fold>
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        manager.send();
    }//GEN-LAST:event_jButton1ActionPerformed

    // <editor-fold defaultstate="collapsed" desc="NetBeans Generated Code"> 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    
    // </editor-fold> 
    
}
