
/** required package class namespace */
package year2020.cs40s.awards.userinterfaces;

import year2020.cs40s.awards.userinterfaces.controllers.CoursesDataUIController;
import javax.swing.JFrame;
import year2020.cs40s.awards.io.Dialogs;


/**
 * CoursesDataUIView.java - description
 *
 * @author Mr. Wachs
 * @since 20-May-2020, 9:06:10 PM
 */
public class CoursesDataUIView extends javax.swing.JFrame 
{

    private CoursesDataUIController controller;
    
    /** 
     * Default constructor, set class properties, creates new form CoursesDataUIView 
     */
    public CoursesDataUIView(JFrame userInterface, int index) {
        initComponents();
        controller = new CoursesDataUIController(
                jButton1,
                jButton2,
                jButton3,
                jLabel1,
                jLabel2,
                jLabel3,
                jList1,
                jScrollPane1,
                this,
                userInterface,
                index
        );
    }

    /** 
     * This method is called from within the constructor to initialize the
     * form.
     * 
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText(" ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 20, 320, 40);

        jLabel2.setText("Students in Course:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 470, 40);

        jLabel3.setText("Course Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 140, 40);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 120, 470, 280);

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 420, 150, 50);

        jButton2.setText("Sort by grade");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 420, 150, 50);

        jButton3.setText("Sort by name");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 420, 150, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        controller.sortByName();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        controller.sortByGrade();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller.goBack();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
