package yearOthers.polygonmath;


import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JPanel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on 11-Apr-2011, 9:33:50 AM
 */

/**
 *
 * @author lwachs
 */
public class GUI extends javax.swing.JFrame {

    int setValue = 0;
    Graphics g;

    /** Creates new form GUI */
    public GUI() {
        initComponents();
        initDatastructures();
        fraGraphics = new MyPanel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fraBackground = new javax.swing.JPanel();
        sliNumberOfSides = new javax.swing.JSlider();
        lblNumberOfSides = new javax.swing.JLabel();
        fraGraphics = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        fraBackground.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fraBackground.setLayout(null);

        sliNumberOfSides.setMaximum(500);
        sliNumberOfSides.setMinimum(1);
        sliNumberOfSides.setPaintLabels(true);
        sliNumberOfSides.setPaintTicks(true);
        sliNumberOfSides.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliNumberOfSidesStateChanged(evt);
            }
        });
        sliNumberOfSides.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sliNumberOfSidesPropertyChange(evt);
            }
        });
        sliNumberOfSides.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                sliNumberOfSidesVetoableChange(evt);
            }
        });
        fraBackground.add(sliNumberOfSides);
        sliNumberOfSides.setBounds(10, 40, 720, 50);

        lblNumberOfSides.setText("Number of Sides:");
        fraBackground.add(lblNumberOfSides);
        lblNumberOfSides.setBounds(20, 20, 240, 14);

        fraGraphics.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fraGraphics.setLayout(null);
        fraBackground.add(fraGraphics);
        fraGraphics.setBounds(20, 90, 700, 450);

        getContentPane().add(fraBackground);
        fraBackground.setBounds(10, 10, 740, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliNumberOfSidesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sliNumberOfSidesPropertyChange
        sliderChange();
    }//GEN-LAST:event_sliNumberOfSidesPropertyChange

    private void sliNumberOfSidesVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_sliNumberOfSidesVetoableChange
        sliderChange();
    }//GEN-LAST:event_sliNumberOfSidesVetoableChange

    private void sliNumberOfSidesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliNumberOfSidesStateChanged
        sliderChange();
    }//GEN-LAST:event_sliNumberOfSidesStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fraBackground;
    private javax.swing.JPanel fraGraphics;
    private javax.swing.JLabel lblNumberOfSides;
    private javax.swing.JSlider sliNumberOfSides;
    // End of variables declaration//GEN-END:variables

    private void initDatastructures() {
        this.setSize(775,630);
    }

    private void sliderChange() {
        int value = sliNumberOfSides.getValue();
        lblNumberOfSides.setText("Number of Sides: " + value);
        setValue = value;
        changePolygon();
    }

    private void changePolygon() {
        fraGraphics.repaint();
        
//        fraGraphics.paintComponents(g);
//        g = this.getGraphics();
//        g.setColor(Color.red);
//        if (setValue != 0) {
//            g.fillOval(0, 0, setValue, setValue);
//        }
//        //fraGraphics.paint(g);
//        fraGraphics.paintComponents(g);
//        fraGraphics.repaint();
    }


    public class MyPanel extends JPanel {

        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            // your drawing code here
            //g = this.getGraphics();
            g.setColor(Color.red);
            if (setValue != 0) {
                g.fillOval(0, 0, setValue, setValue);
            }
            //fraGraphics.paint(g);
            //fraGraphics.paintComponents(g);
        }
    }


}
