
/** required package class namespace */
package year2021.cs40s.familytree.userinterfaces;

import year2021.cs40s.familytree.datastructures.Globals;
import java.net.URL;
import javax.swing.ImageIcon;
import year2021.cs40s.familytree.tools.Images;



public class PlanningUI extends javax.swing.JFrame 
{
    
    // <editor-fold defaultstate="collapsed" desc="All NetBeans Generated Code collapsed in NetBeans"> 

    /** 
     * Default constructor, set class properties, creates new form PlanningUI 
     */
    public PlanningUI() {
        initComponents();
        startup();
    }

    /** 
     * This method is called from within the constructor to initialize the
     * form.
     * 
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setText("< Previous Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 410, 190, 50);

        jButton2.setText("Next Image >");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 410, 190, 50);

        jButton4.setText("Return To Main Screen");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(220, 410, 200, 50);

        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 600, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        returnToMainScreen();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        previousImage();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        nextImage();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closeWindow();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    // </editor-fold>
    
    private final String[] IMAGE_FILES = {
        "/year2021/cs40s/familytree/media/IMG_1190.JPG",
        "/year2021/cs40s/familytree/media/IMG_1191.JPG",
        "/year2021/cs40s/familytree/media/IMG_1192.JPG",
        "/year2021/cs40s/familytree/media/IMG_1193.JPG",
        "/year2021/cs40s/familytree/media/IMG_1194.JPG",
        "/year2021/cs40s/familytree/media/IMG_1195.JPG",
        "/year2021/cs40s/familytree/media/IMG_1196.JPG",
        "/year2021/cs40s/familytree/media/IMG_1197.JPG",
        "/year2021/cs40s/familytree/media/IMG_1198.JPG",
        "/year2021/cs40s/familytree/media/IMG_1199.JPG"        
    };    
    private URL[] images;
    private int count;
    
    
    /**
     * When the constructor for this class is call (when the UI appears), set
     * the staring conditions for this class
     */
    private void startup() {
        count  = 0;
        images = new URL[IMAGE_FILES.length];
        for (int i = 0; i < images.length; i++) {
            images[i] = getClass().getResource(IMAGE_FILES[i]);
        }
        jLabel2.setIcon(new ImageIcon(images[0]));
        Images.resizeToContainer(jLabel2);
        Globals.startup(this, 645, 510);
    }
    
    private void previousImage() {
        count--;
        if (count < 0) count = images.length - 1;
        jLabel2.setIcon(new ImageIcon(images[count])); 
        Images.resizeToContainer(jLabel2);
    }

    private void nextImage() {
        count++;
        if (count > images.length - 1) count = 0;
        jLabel2.setIcon(new ImageIcon(images[count]));
        Images.resizeToContainer(jLabel2);
    }
    
    /**
     * The associated code with the button to return to main UI
     */
    private void returnToMainScreen() {
        new WelcomeUI();                            // Launch other UI
        this.dispose();                             // Dispose of this UI
    }
    
    /**
     * The associated code with the user closing this UI (by clicking the "X")
     */
    private void closeWindow() {
        Globals.end();
    }

}
