/*
 *  Mr. Wachs' classes - Java Computer Science learning file MainUI.java
 *  for project FinalExamples on 12-Apr-2019 at 8:58:06 AM by lawrence.wachs
 */


/** required package class namespace */
package year2019.cs40s.namepicker;


/**
 * MainUI.java - 
 *
 * @author Mr. Wachs 
 * @since 12-Apr-2019 
 */
public class MainModel extends javax.swing.JFrame 
{

    private MainController controller;
    
    /** Creates new form MainUI */
    public MainModel() {
        initComponents();
        controller = new MainController(
                this,
                jButton1,jButton10,jButton11,
                jButton2,jButton3,jButton4,jButton5,
                jButton6,jButton7,jButton8,jButton9,
                jLabel1,jLabel2,jList1,jList2,jMenu2,
                jMenuBar2,jMenuItem1,jMenuItem2,
                jPanel1,jPanel2,jScrollPane1,jScrollPane2        
        );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chosen Names List"));
        jPanel1.setLayout(null);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 30, 350, 230);

        jButton2.setText("Remove Selected Name from Chosen");
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 320, 350, 40);

        jButton5.setText("Clear List");
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 470, 350, 40);

        jButton9.setText("Open List from File");
        jPanel1.add(jButton9);
        jButton9.setBounds(10, 420, 350, 40);

        jButton6.setText("Save List to File");
        jPanel1.add(jButton6);
        jButton6.setBounds(10, 370, 350, 40);

        jButton10.setText("Move Selected Name Back to Unchosen");
        jPanel1.add(jButton10);
        jButton10.setBounds(10, 270, 350, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(400, 170, 370, 520);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Unchosen Names List"));
        jPanel2.setLayout(null);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 350, 230);

        jButton1.setText("Clear List");
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 470, 350, 40);

        jButton3.setText("Add Name To Unchosen List");
        jPanel2.add(jButton3);
        jButton3.setBounds(10, 320, 350, 40);

        jButton4.setText("Save List to File");
        jPanel2.add(jButton4);
        jButton4.setBounds(10, 370, 350, 40);

        jButton7.setText("Remove Selected Name from Unchosen");
        jPanel2.add(jButton7);
        jButton7.setBounds(10, 270, 350, 40);

        jButton8.setText("Open List from File");
        jPanel2.add(jButton8);
        jButton8.setBounds(10, 420, 350, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 170, 370, 520);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setText("Name Picker");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 740, 50);

        jLabel2.setText("The unchosen list of names on the left is all names not yet chosen. You can add and remove names from this list. As well, you can save this list to a file, or open a previously saved list from a file. The list of names on the right are the names that have been randomly drawn from the list on the left. Once a name is in the chosen list, it cannot be drawn again (even if it appears multiple times in the unchosen list). This list can also be altered, saved or opened. Click the draw name button to draw a name each time.");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 740, 100);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jButton11.setText("DRAW NAME");
        getContentPane().add(jButton11);
        jButton11.setBounds(200, 700, 360, 60);

        jMenu2.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Settings");
        jMenu2.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenu2.add(jMenuItem1);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
