
/** required package class namespace */
package year2019.cs40s.namepicker;


/**
 * MainUI.java - 
 *
 * @author Mr. Wachs 
 * @since 12-Apr-2019 
 */
public class MainModel extends javax.swing.JFrame 
{

    private MainController controller;
    
    /** Creates new form MainUI */
    public MainModel() {
        initComponents();
        controller = new MainController(
                this,addNameUnchosenButton,chosenNamesListBox,chosenNamesPanel,
                chosenNamesScrollPane,clearListChosenButton,
                clearListUnchosenButton,drawNameButton,exitMenuItem,
                fileMenu,instructionsLabel,mainMenuBar,moveBackChosenButton,
                openListChosenButton,openListUnchosenButton,
                removeNameChosenButton,removeSelectedUnchosenButton,
                saveListChosenButton,saveListUnchosenButton,settingsMenuItem,
                titleLabel,unchosenNamesListBox,unchosenNamesPanel,
                unchosenNamesScrollPane        
        );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chosenNamesPanel = new javax.swing.JPanel();
        chosenNamesScrollPane = new javax.swing.JScrollPane();
        chosenNamesListBox = new javax.swing.JList<>();
        removeNameChosenButton = new javax.swing.JButton();
        clearListChosenButton = new javax.swing.JButton();
        openListChosenButton = new javax.swing.JButton();
        saveListChosenButton = new javax.swing.JButton();
        moveBackChosenButton = new javax.swing.JButton();
        unchosenNamesPanel = new javax.swing.JPanel();
        unchosenNamesScrollPane = new javax.swing.JScrollPane();
        unchosenNamesListBox = new javax.swing.JList<>();
        clearListUnchosenButton = new javax.swing.JButton();
        addNameUnchosenButton = new javax.swing.JButton();
        saveListUnchosenButton = new javax.swing.JButton();
        removeSelectedUnchosenButton = new javax.swing.JButton();
        openListUnchosenButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        instructionsLabel = new javax.swing.JLabel();
        drawNameButton = new javax.swing.JButton();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        settingsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        chosenNamesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Chosen Names List"));
        chosenNamesPanel.setLayout(null);

        chosenNamesListBox.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        chosenNamesScrollPane.setViewportView(chosenNamesListBox);

        chosenNamesPanel.add(chosenNamesScrollPane);
        chosenNamesScrollPane.setBounds(10, 30, 350, 230);

        removeNameChosenButton.setText("Remove Selected Name from Chosen");
        chosenNamesPanel.add(removeNameChosenButton);
        removeNameChosenButton.setBounds(10, 320, 350, 40);

        clearListChosenButton.setText("Clear List");
        chosenNamesPanel.add(clearListChosenButton);
        clearListChosenButton.setBounds(10, 470, 350, 40);

        openListChosenButton.setText("Open List from File");
        chosenNamesPanel.add(openListChosenButton);
        openListChosenButton.setBounds(10, 420, 350, 40);

        saveListChosenButton.setText("Save List to File");
        chosenNamesPanel.add(saveListChosenButton);
        saveListChosenButton.setBounds(10, 370, 350, 40);

        moveBackChosenButton.setText("Move Selected Name Back to Unchosen");
        chosenNamesPanel.add(moveBackChosenButton);
        moveBackChosenButton.setBounds(10, 270, 350, 40);

        getContentPane().add(chosenNamesPanel);
        chosenNamesPanel.setBounds(400, 170, 370, 520);

        unchosenNamesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Unchosen Names List"));
        unchosenNamesPanel.setLayout(null);

        unchosenNamesListBox.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        unchosenNamesScrollPane.setViewportView(unchosenNamesListBox);

        unchosenNamesPanel.add(unchosenNamesScrollPane);
        unchosenNamesScrollPane.setBounds(10, 30, 350, 230);

        clearListUnchosenButton.setText("Clear List");
        unchosenNamesPanel.add(clearListUnchosenButton);
        clearListUnchosenButton.setBounds(10, 470, 350, 40);

        addNameUnchosenButton.setText("Add Name To Unchosen List");
        unchosenNamesPanel.add(addNameUnchosenButton);
        addNameUnchosenButton.setBounds(10, 320, 350, 40);

        saveListUnchosenButton.setText("Save List to File");
        unchosenNamesPanel.add(saveListUnchosenButton);
        saveListUnchosenButton.setBounds(10, 370, 350, 40);

        removeSelectedUnchosenButton.setText("Remove Selected Name from Unchosen");
        unchosenNamesPanel.add(removeSelectedUnchosenButton);
        removeSelectedUnchosenButton.setBounds(10, 270, 350, 40);

        openListUnchosenButton.setText("Open List from File");
        unchosenNamesPanel.add(openListUnchosenButton);
        openListUnchosenButton.setBounds(10, 420, 350, 40);

        getContentPane().add(unchosenNamesPanel);
        unchosenNamesPanel.setBounds(20, 170, 370, 520);

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        titleLabel.setText("Name Picker");
        getContentPane().add(titleLabel);
        titleLabel.setBounds(30, 10, 740, 50);

        instructionsLabel.setText("The unchosen list of names on the left is all names not yet chosen. You can add and remove names from this list. As well, you can save this list to a file, or open a previously saved list from a file. The list of names on the right are the names that have been randomly drawn from the list on the left. Once a name is in the chosen list, it cannot be drawn again (even if it appears multiple times in the unchosen list). This list can also be altered, saved or opened. Click the draw name button to draw a name each time.");
        instructionsLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(instructionsLabel);
        instructionsLabel.setBounds(30, 60, 740, 100);

        drawNameButton.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        drawNameButton.setText("DRAW NAME");
        getContentPane().add(drawNameButton);
        drawNameButton.setBounds(200, 700, 360, 60);

        fileMenu.setText("File");

        settingsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        settingsMenuItem.setText("Settings");
        fileMenu.add(settingsMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setText("Exit");
        fileMenu.add(exitMenuItem);

        mainMenuBar.add(fileMenu);

        setJMenuBar(mainMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNameUnchosenButton;
    private javax.swing.JList<String> chosenNamesListBox;
    private javax.swing.JPanel chosenNamesPanel;
    private javax.swing.JScrollPane chosenNamesScrollPane;
    private javax.swing.JButton clearListChosenButton;
    private javax.swing.JButton clearListUnchosenButton;
    private javax.swing.JButton drawNameButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel instructionsLabel;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JButton moveBackChosenButton;
    private javax.swing.JButton openListChosenButton;
    private javax.swing.JButton openListUnchosenButton;
    private javax.swing.JButton removeNameChosenButton;
    private javax.swing.JButton removeSelectedUnchosenButton;
    private javax.swing.JButton saveListChosenButton;
    private javax.swing.JButton saveListUnchosenButton;
    private javax.swing.JMenuItem settingsMenuItem;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JList<String> unchosenNamesListBox;
    private javax.swing.JPanel unchosenNamesPanel;
    private javax.swing.JScrollPane unchosenNamesScrollPane;
    // End of variables declaration//GEN-END:variables

}
