
/** required package class namespace */
package year2018.cs30s.moregaming.spaceinvaders;

/** required imports */
import mainpackage.Examples2018;
import mainpackage.MainClass;
import year2018.cs30s.gametools.Image;

/**
 * SpaceInvadersGUI.java - the user interface for the space invaders game
 *
 * @author Mr. Wachs
 * @since May 28, 2018 
 * @instructor Mr. Wachs
 */
public class SpaceInvadersGUI extends javax.swing.JFrame 
{

    private Engine engine;
    
    /** 
     * Creates new form SpaceInvadersGUI 
     */
    public SpaceInvadersGUI() {
        initComponents();
        Image   backgroundImage   = new Image(jLabel18);        
        Image   heroShipImage     = new Image(jLabel27);
        Image   heroBulletImage   = new Image(jLabel28);
        Image[] baseImages        = {
            new Image(jLabel16),
            new Image(jLabel17),
            new Image(jLabel13)
        };
        Image[] enemyShipImages   = {
            new Image(jLabel23),
            new Image(jLabel24),
            new Image(jLabel25),
            new Image(jLabel26),
            new Image(jLabel15)
        };
        Image[] enemyBulletImages = {
            new Image(jLabel29),
            new Image(jLabel30),
            new Image(jLabel31),
            new Image(jLabel32),
            new Image(jLabel22)
        };  
        Image[] wallImages        = {
            new Image(jLabel21),
            new Image(jLabel20),
            new Image(jLabel14),
            new Image(jLabel19)
        };          
        engine = new Engine(
                backgroundImage,
                heroShipImage,
                heroBulletImage,
                baseImages,
                enemyShipImages,
                enemyBulletImages,
                wallImages,
                this);        
        MainClass.frameTool.startup(this, 
                Constants.SPACE_INVADERS_UI_TITLE, 
                Constants.SPACE_INVADERS_UI_WIDTH, 
                Constants.SPACE_INVADERS_UI_HEIGHT, 
                false, 
                true,
                false,
                false,
                Constants.SPACE_INVADERS_UI_BACK_COLOR,
                Examples2018.SPACE_INVADERS_ICON);
    }

    // <editor-fold defaultstate="collapsed" desc="NetBeans Visual Editor Generated Code">  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("base");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel13);
        jLabel13.setBounds(700, 340, 160, 120);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("wall");
        jLabel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 0, 30, 690);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("wall");
        jLabel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 0, 860, 30);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("wall");
        jLabel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel20);
        jLabel20.setBounds(890, 0, 30, 690);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("wall");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 660, 860, 30);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("enemy");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel15);
        jLabel15.setBounds(710, 50, 100, 60);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("base");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel16);
        jLabel16.setBounds(60, 340, 160, 120);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("base");
        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel17);
        jLabel17.setBounds(390, 340, 160, 120);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("enemy bullet");
        jLabel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel22);
        jLabel22.setBounds(730, 250, 20, 20);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("enemy");
        jLabel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel23);
        jLabel23.setBounds(110, 50, 100, 60);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("enemy");
        jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel24);
        jLabel24.setBounds(260, 50, 100, 60);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("enemy");
        jLabel25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel25);
        jLabel25.setBounds(410, 50, 100, 60);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("enemy");
        jLabel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel26);
        jLabel26.setBounds(560, 50, 100, 60);

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("hero");
        jLabel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel27);
        jLabel27.setBounds(410, 550, 120, 100);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("hero bullet");
        jLabel28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel28);
        jLabel28.setBounds(280, 470, 20, 20);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("enemy bullet");
        jLabel29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel29);
        jLabel29.setBounds(140, 250, 20, 20);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("enemy bullet");
        jLabel30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel30);
        jLabel30.setBounds(290, 250, 20, 20);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("enemy bullet");
        jLabel31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel31);
        jLabel31.setBounds(440, 250, 20, 20);

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("enemy bullet");
        jLabel32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel32);
        jLabel32.setBounds(590, 250, 20, 20);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("background");
        jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 0, 920, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // </editor-fold> 
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        engine.keyPress(evt);
    }//GEN-LAST:event_formKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        MainClass.gamesPlayed++;
        Examples2018.menu();
    }//GEN-LAST:event_formWindowClosing

    // <editor-fold defaultstate="collapsed" desc="NetBeans Visual Editor Generated Code">  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    // End of variables declaration//GEN-END:variables

    // </editor-fold> 
    
}
