
/** required package */
package year2018.cs30s.moregaming.spaceinvaders;

/** required imports */
import javax.swing.JLabel;

/**
 * SpaceInvadersGUI.java - the user interface for the space invaders game
 * @author Mr. Wachs' Computer Science Student 
 * @since 18-Jan-2016
 * @version 1.0
 * @instructor Mr. Wachs
 */
public class SpaceInvadersGUI extends javax.swing.JFrame 
{

    private Engine engine;
    
    /** Creates new form SpaceInvadersGUI */
    public SpaceInvadersGUI() {
        initComponents();
        JLabel   backgroundImage   = jLabel18;        
        JLabel   heroShipImage     = jLabel27;
        JLabel   heroBulletImage   = jLabel28;
        JLabel[] baseImages        = {jLabel16,jLabel17,jLabel13};
        JLabel[] enemyShipImages   = {jLabel23,jLabel24,jLabel25,jLabel26,jLabel15};
        JLabel[] enemyBulletImages = {jLabel29,jLabel30,jLabel31,jLabel32,jLabel22};  
        JLabel[] wallImages        = {jLabel21,jLabel20,jLabel14,jLabel19};          
        engine = new Engine(
                backgroundImage,
                heroShipImage,
                heroBulletImage,
                baseImages,
                enemyShipImages,
                enemyBulletImages,
                wallImages);
        this.setSize(1050,720);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    // <editor-fold defaultstate="collapsed" desc="NetBeans Visual Editor Generated Code">  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("base");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel13);
        jLabel13.setBounds(700, 390, 160, 90);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("wall");
        jLabel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 0, 30, 690);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("wall");
        jLabel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel21);
        jLabel21.setBounds(30, 0, 860, 30);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("wall");
        jLabel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel20);
        jLabel20.setBounds(890, 0, 30, 690);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("wall");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 660, 860, 30);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("enemy");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel15);
        jLabel15.setBounds(720, 130, 100, 110);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("base");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel16);
        jLabel16.setBounds(60, 390, 160, 90);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("base");
        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel17);
        jLabel17.setBounds(390, 390, 160, 90);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("enemy bullet");
        jLabel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel22);
        jLabel22.setBounds(730, 250, 60, 80);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("enemy");
        jLabel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel23);
        jLabel23.setBounds(120, 130, 100, 110);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("enemy");
        jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel24);
        jLabel24.setBounds(270, 130, 100, 110);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("enemy");
        jLabel25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel25);
        jLabel25.setBounds(420, 130, 100, 110);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("enemy");
        jLabel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel26);
        jLabel26.setBounds(570, 130, 100, 110);

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("hero");
        jLabel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel27);
        jLabel27.setBounds(410, 550, 120, 100);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("hero bullet");
        jLabel28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel28);
        jLabel28.setBounds(280, 470, 60, 80);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("enemy bullet");
        jLabel29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel29);
        jLabel29.setBounds(140, 250, 60, 80);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("enemy bullet");
        jLabel30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel30);
        jLabel30.setBounds(290, 250, 60, 80);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("enemy bullet");
        jLabel31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel31);
        jLabel31.setBounds(440, 250, 60, 80);

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("enemy bullet");
        jLabel32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel32);
        jLabel32.setBounds(590, 250, 60, 80);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("background");
        jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 0, 920, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // </editor-fold> 
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        engine.keyPress(evt);
    }//GEN-LAST:event_formKeyPressed

    // <editor-fold defaultstate="collapsed" desc="NetBeans Visual Editor Generated Code">  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    // End of variables declaration//GEN-END:variables

    // </editor-fold> 
    
}
